name: scan-repo
on:
  #schedule:
   # -cron: "*/5 * * * *"

concurrency:
  group: scan-repo
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Read changes to simplify repo
        run: |
          set -euo pipefail
          curl -fsSL \ 
        #  "https://github.com/SimplifyJobs/Summer2026-Internships/blob/dev/README.md#-data-science-ai--machine-learning-internship-roles" \
        # -o temp.html